class FirstsFollows:

    def __init__(self):
        print('FIRST FOLLOW CLASS')

    @staticmethod
    def getFollows(state):
        follows = {'START': ['endOfFile($)'],
                   'HEADER1': ['endOfFile($)'],
                   'HEADER2': ['endOfFile($)'],
                   'HEADER3': ['endOfFile($)'],
                   'METHODS': ['endOfFile($)'],
                   'PROCCHOICE': ['endOfFile($)'],
                   'VARIABLE': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                'while', 'if', 'return', '}', ',', ')'],
                   'SCOPEVARIABLE': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', '[',
                                     '(', '.', '++', '--', '=', 'identificador', 'global', 'local', 'typedef', 'struct',
                                     'print', 'read', 'while', 'if', 'return', '}', ')'],
                   'VECTMATINDEX': [']'],
                   'DATATYPE': ['identificador'],
                   'CONTELEMENT': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', '++',
                                   '--', '=', 'identificador', 'global', 'local', 'typedef', 'struct', 'print', 'read',
                                   'while', 'if', 'return', '}', ')', '[', '(', '.'],
                   'STRUCTE1': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', '++', '--',
                                '=', 'identificador', 'global', 'local', 'typedef', 'struct', 'print', 'read', 'while',
                                'if', 'return', '}', ')', '[', '(', '.'],
                   'MATRIZE1': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', '++', '--',
                                '=', 'identificador', 'global', 'local', 'typedef', 'struct', 'print', 'read', 'while',
                                'if', 'return', '}', ')', '[', '(', '.'],
                   'MATRIZE2': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', '++', '--',
                                '=', 'identificador', 'global', 'local', 'typedef', 'struct', 'print', 'read', 'while',
                                'if', 'return', '}', ')', '[', '(', '.'],
                   'VARDECLARATION': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                      'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'FIRSTVAR': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'NEXTVAR': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                               'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'CONTINUESOS': ['identificador'],
                   'VARID': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador', 'global',
                             'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'VAREXP': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                              'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'STRUCTURE': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                 'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'CONTMATRIX': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                  'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'INITARRAY': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                 'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'NEXTARRAY': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                 'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'INITMATRIX': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                  'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'MATRIXVALUE': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                   'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'NEXTMATRIX': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                  'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'NEXT': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador', 'global',
                            'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'VERIFVAR': ['typedef', 'struct', 'const', 'procedure', 'function', 'return', 'identificador',
                                'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'CONSTDECLARATION': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                        'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'FIRSTCONST': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                  'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'CONTINUECONSTSOS': ['identificador'],
                   'NEXTCONST': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                 'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'CONSTID': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador', 'global',
                               'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'CONSTEXP': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'STRUCTURECONST': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                      'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'NEXTCONSTVETOR': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                      'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'INITCONSTMATRIX': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                       'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'MATRIXCONSTVALUE': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                        'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'NEXTCONSTMATRIZ': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                       'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'NEXTCONST2': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                  'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'VERIFCONST': ['typedef', 'struct', 'var', 'procedure', 'function', 'return', 'identificador',
                                  'global', 'local', '++', '--', 'print', 'read', 'while', 'if', '}'],
                   'FUNCTION': ['procedure', 'function'],
                   'CONTINUEFUNCTION': ['procedure', 'function'],
                   'PARAMETERS': ['{'],
                   'PARAMLOOP': ['{'],
                   'BLOCKFUNCTION': ['procedure', 'function'],
                   'BLOCKFUNCTIONCONTENT': [';'],
                   'FUNCTIONCONTENT': [';'],
                   'CONTENT1': [';'],
                   'CONTENT2': [';'],
                   'CONTENT3': [';'],
                   'STRUCTUREDECLARATION': ['typedef', 'struct', 'var', 'const', 'procedure', 'function',
                                            'identificador', 'global', 'local', '++', '--', 'print', 'read', 'while',
                                            'if', 'return', '}'],
                   'STRUCTVARS': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                  'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'FIRSTSTRUCTVAR': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                      'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'STRUCTVARID': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                   'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'NEXTSTRUCTVAR': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                     'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'STRUCTVAREXP': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                    'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'STRUCTMATRIX': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                    'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'CONTSTRUCTMATRIX': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                        'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'EXPRESSION': [',', ';', ']', ')'],
                   'LOGEXP': [',', ';', ']', ')'],
                   'LOGICSYMBOL': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global',
                                   'local'],
                   'RELEXP': ['&&', '||', ',', ';', ']', ')'],
                   'RELEXP2': ['&&', '||', ',', ';', ']', ')'],
                   'RELSYMBOL': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global',
                                 'local'],
                   'ARITEXP1': ['>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', ')'],
                   'ARITEXP2': ['>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', ')'],
                   'ARITSYMB1': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global',
                                 'local'],
                   'TERM': ['+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', ')'],
                   'TERM2': ['+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', ')'],
                   'ARITSYMB2': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global',
                                 'local'],
                   'OPERATE': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', ')'],
                   'CONTOPERATE': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']', ')'],
                   'TYPEDEFDECLARATION': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                          'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'CONTTYPEDEFDEC': ['typedef', 'struct', 'var', 'const', 'procedure', 'function', 'identificador',
                                      'global', 'local', '++', '--', 'print', 'read', 'while', 'if', 'return', '}'],
                   'STARTPROCEDURE': ['endOfFile($)'],
                   'PROCEDURE': ['procedure', 'function'],
                   'PROCPARAM': ['{'],
                   'PROCCONTENT': ['endOfFile($)', 'procedure', 'function'],
                   'PROCCONTENT2': ['endOfFile($)', 'procedure', 'function'],
                   'PROCCONTENT3': ['endOfFile($)', 'procedure', 'function'],
                   'PROCCONTENT4': ['endOfFile($)', 'procedure', 'function'],
                   'CODE': ['return', '}'],
                   'COMMAND': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                               'while', 'if', 'return', '}'],
                   'OTHERCOMMANDS': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                                     'read', 'while', 'if', 'return', '}'],
                   'OTHERCOMMANDS2': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                                      'read', 'while', 'if', 'return', '}'],
                   'PRINTFUNC': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                 'while', 'if', 'return', '}'],
                   'PRINTFUNCABLELIST': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                                         'read', 'while', 'if', 'return', '}'],
                   'PRINTFUNCABLE': [',', ')'],
                   'NEXTPRINTFUNCVALUE': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                                          'read', 'while', 'if', 'return', '}'],
                   'ASSIGNMENT': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                  'while', 'if', 'return', '}'],
                   'FUNCTIONCALL': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']',
                                    'identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                                    'read', 'while', 'if', 'return', '}', ')'],
                   'CONTFCALL': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']',
                                 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                 'while', 'if', 'return', '}', ')'],
                   'FCALLPARAMS': ['*', '/', '+', '-', '>', '<', '==', '<=', '>=', '&&', '||', ',', ';', ']',
                                   'identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                   'while', 'if', 'return', '}', ')'],
                   'READ': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                            'while', 'if', 'return', '}'],
                   'READPARAMS': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                  'while', 'if', 'return', '}'],
                   'READLOOP': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                'while', 'if', 'return', '}'],
                   'WHILEFUNC': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                 'while', 'if', 'return', '}'],
                   'CONDITIONAL': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                   'while', 'if', 'return', '}'],
                   'ELSEPART': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                                'while', 'if', 'return', '}'],

                   }
        return follows[state]

    @staticmethod
    def getFirsts(state):
        firsts = {'START': ['typedef', 'struct', 'var', 'const', 'procedure', 'function'],
                  'HEADER1': ['typedef', 'struct', 'const', 'procedure', 'function'],
                  'HEADER2': ['typedef', 'struct', 'var', 'procedure', 'function'],
                  'HEADER3': ['typedef', 'struct', 'procedure', 'function'],
                  'METHODS': ['procedure', 'function'],
                  'PROCCHOICE': ['start', 'identificador'],
                  'VARIABLE': ['identificador', 'global', 'local'],
                  'SCOPEVARIABLE': ['global', 'local'],
                  'VECTMATINDEX': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global',
                                   'local'],
                  'DATATYPE': ['int', 'real', 'string', 'boolean', 'identificador'],
                  'CONTELEMENT': ['[', '.', 'vazio'],
                  'STRUCTE1': ['.'],
                  'MATRIZE1': ['[', '.', 'vazio'],
                  'MATRIZE2': ['.', 'vazio'],
                  'VARDECLARATION': ['var'],
                  'FIRSTVAR': ['struct', 'int', 'real', 'string', 'boolean', 'identificador'],
                  'NEXTVAR': ['}', 'struct', 'int', 'real', 'string', 'boolean', 'identificador'],
                  'CONTINUESOS': ['struct', 'int', 'real', 'string', 'boolean', 'identificador'],
                  'VARID': ['identificador'],
                  'VAREXP': [',', '=', ';', '['],
                  'STRUCTURE': ['[', '=', ',', ';'],
                  'CONTMATRIX': ['=', ',', ';'],
                  'INITARRAY': ['['],
                  'NEXTARRAY': [',', ']'],
                  'INITMATRIX': ['['],
                  'MATRIXVALUE': ['['],
                  'NEXTMATRIX': [',', ']'],
                  'NEXT': [',', ']'],
                  'VERIFVAR': [',', ';'],
                  'CONSTDECLARATION': ['const'],
                  'FIRSTCONST': ['struct', 'int', 'real', 'string', 'boolean', 'identificador'],
                  'CONTINUECONSTSOS': ['struct', 'int', 'real', 'string', 'boolean', 'identificador'],
                  'NEXTCONST': ['struct', 'int', 'real', 'string', 'boolean', 'identificador', '}'],
                  'CONSTID': ['identificador'],
                  'CONSTEXP': ['=', '['],
                  'STRUCTURECONST': ['[', '='],
                  'NEXTCONSTVETOR': [',', ']'],
                  'INITCONSTMATRIX': ['['],
                  'MATRIXCONSTVALUE': ['['],
                  'NEXTCONSTMATRIZ': [',', ']'],
                  'NEXTCONST2': [',', ']'],
                  'VERIFCONST': [',', ';'],
                  'FUNCTION': ['function'],
                  'CONTINUEFUNCTION': [')', 'int', 'real', 'string', 'boolean', 'identificador', 'struct'],
                  'PARAMETERS': ['int', 'real', 'string', 'boolean', 'identificador', 'struct'],
                  'PARAMLOOP': [',', ')'],
                  'BLOCKFUNCTION': ['{'],
                  'BLOCKFUNCTIONCONTENT': ['var', 'const', 'return', 'identificador', 'global', 'local', 'typedef',
                                           'struct', '++', '--', 'print', 'read', 'while', 'if'],
                  'FUNCTIONCONTENT': ['return', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--',
                                      'print', 'read', 'while', 'if'],
                  'CONTENT1': ['const', 'return', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--',
                               'print', 'read', 'while', 'if'],
                  'CONTENT2': ['var', 'return', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--',
                               'print', 'read', 'while', 'if'],
                  'CONTENT3': ['return', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                               'read', 'while', 'if'],
                  'STRUCTUREDECLARATION': ['struct'],
                  'STRUCTVARS': ['{', 'extends'],
                  'FIRSTSTRUCTVAR': ['int', 'real', 'string', 'boolean', 'identificador'],
                  'STRUCTVARID': ['identificador'],
                  'NEXTSTRUCTVAR': ['int', 'real', 'string', 'boolean', 'identificador', '}'],
                  'STRUCTVAREXP': [',', ';', '['],
                  'STRUCTMATRIX': ['[', ',', ';'],
                  'CONTSTRUCTMATRIX': [',', ';'],
                  'EXPRESSION': ['!', '(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global',
                                 'local'],
                  'LOGEXP': ['vazio', '&&', '||'],
                  'LOGICSYMBOL': ['&&', '||'],
                  'RELEXP': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global', 'local'],
                  'RELEXP2': ['vazio', '>', '<', '==', '<=', '>='],
                  'RELSYMBOL': ['>', '<', '==', '<=', '>='],
                  'ARITEXP1': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global',
                               'local'],
                  'ARITEXP2': ['vazio', '+', '-'],
                  'ARITSYMB1': ['+', '-'],
                  'TERM': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global', 'local'],
                  'TERM2': ['vazio', '*', '/'],
                  'ARITSYMB2': ['*', '/'],
                  'OPERATE': ['(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador', 'global', 'local'],
                  'CONTOPERATE': ['[', '(', '.', 'vazio'],
                  'TYPEDEFDECLARATION': ['typedef'],
                  'CONTTYPEDEFDEC': ['int', 'real', 'string', 'boolean', 'identificador', 'struct'],
                  'STARTPROCEDURE': ['('],
                  'PROCEDURE': ['identificador'],
                  'PROCPARAM': ['int', 'real', 'string', 'boolean', 'identificador', 'struct', ')'],
                  'PROCCONTENT': ['var', 'const', '}', 'identificador', 'global', 'local', 'typedef', 'struct', '++',
                                  '--', 'print', 'read', 'while', 'if'],
                  'PROCCONTENT2': ['const', '}', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--',
                                   'print', 'read', 'while', 'if'],
                  'PROCCONTENT3': ['var', '}', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--',
                                   'print', 'read', 'while', 'if'],
                  'PROCCONTENT4': ['}', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                                   'read', 'while', 'if'],
                  'CODE': ['vazio', 'identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print',
                           'read', 'while', 'if'],
                  'COMMAND': ['identificador', 'global', 'local', 'typedef', 'struct', '++', '--', 'print', 'read',
                              'while', 'if'],
                  'OTHERCOMMANDS': ['[', '(', '.', '++', '--', '='],
                  'OTHERCOMMANDS2': ['++', '--', '='],
                  'PRINTFUNC': ['print'],
                  'PRINTFUNCABLELIST': ['cad_caracteres', 'identificador', 'global', 'local'],
                  'PRINTFUNCABLE': ['cad_caracteres', 'identificador', 'global', 'local'],
                  'NEXTPRINTFUNCVALUE': [',', ')'],
                  'ASSIGNMENT': ['='],
                  'FUNCTIONCALL': ['('],
                  'CONTFCALL': ['!', ')', '(', 'booleano', 'inteiro', 'real', 'cad_caracteres', 'identificador',
                                'global', 'local'],
                  'FCALLPARAMS': [',', ')'],
                  'READ': ['read'],
                  'READPARAMS': ['identificador', 'global', 'local'],
                  'READLOOP': [',', ')'],
                  'WHILEFUNC': ['while'],
                  'CONDITIONAL': ['if'],
                  'ELSEPART': ['else', 'vazio'],
                  }
        return firsts[state]
